apiVersion: v1
kind: Service
metadata:
  name: {{ include "windmill.fullname" . }}
  labels:
    {{- include "windmill.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "windmill.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
