{{- if or (not .Values.adminPassword.existingSecret) (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odoo.fullname" . }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.adminPassword.existingSecret }}
  admin-password: {{ .Values.adminPassword.value | toString | b64enc | quote }}
  {{- end }}
  {{- if not .Values.database.existingSecret }}
  db-password: {{ .Values.database.password | toString | b64enc | quote }}
  {{- end }}
{{- end }}