apiVersion: v2
name: mailpit
description: A Helm chart for deploying Mailpit (a developer mail trap / SMTP catcher) on Kubernetes
type: application
version: 0.1.0
appVersion: "1.21"
home: https://github.com/axllent/mailpit
sources:
  - https://github.com/axllent/mailpit
maintainers:
  - name: Adomi Software, LLC
    email: github@adomisoftware.com
keywords:
  - mail
  - smtp
  - mailpit
  - testing
dependencies:
  - name: platform-lib
    version: 0.1.0
    repository: file://../platform-lib
